package com.toptal.bookshopv2.model;

import lombok.*;
import java.math.BigDecimal;

/**
 * Domain model representing a book in the bookshop catalog.
 *
 * <p>Books are the core product entity of the system. They belong to a {@link Category}
 * (referenced by {@link #categoryId}) and have inventory tracked via {@link #stock}.</p>
 *
 * <h3>Storage:</h3>
 * <p>Stored in-memory via {@link com.toptal.bookshopv2.repository.BookRepository}
 * using a {@link java.util.concurrent.ConcurrentHashMap}.</p>
 *
 * <h3>Stock management:</h3>
 * <ul>
 *   <li>Books with {@code stock <= 0} are excluded from public catalog listings</li>
 *   <li>Stock is decremented atomically during checkout in
 *       {@link com.toptal.bookshopv2.service.CartService#checkout}</li>
 *   <li>Stock cannot be updated via the book update endpoint (admin can only change metadata)</li>
 * </ul>
 *
 * <h3>Access control:</h3>
 * <ul>
 *   <li>Public: browsing and viewing books ({@code GET /api/books})</li>
 *   <li>Admin only: create, update, delete ({@code /api/admin/books})</li>
 * </ul>
 *
 * @author Nitish
 * @version 2.0
 * @see Category
 * @see com.toptal.bookshopv2.repository.BookRepository
 * @see com.toptal.bookshopv2.service.BookService
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Book {

    /** Unique identifier, auto-generated by {@link com.toptal.bookshopv2.repository.BookRepository}. */
    private Long id;

    /** Title of the book. Required field, used for display and sorting. */
    private String title;

    /** Author name. Required field, used for display and sorting. */
    private String author;

    /** Year the book was originally published. Used for sorting and display. */
    private Integer yearPublished;

    /** Retail price of the book. Must be greater than 0. Captured as {@code priceAtPurchase} during checkout. */
    private BigDecimal price;

    /** Current inventory count. Books with {@code stock <= 0} are hidden from the public catalog. */
    private Integer stock;

    /**
     * Foreign key reference to the {@link Category} this book belongs to.
     * Must reference an existing category ID; validated during creation and update.
     */
    private Long categoryId;
}
