package com.toptal.bookshopv2.model;

import lombok.*;
import java.time.LocalDateTime;

/**
 * Domain model representing an item in a user's shopping cart.
 *
 * <p>Each cart item links a {@link User} (by {@link #userId}) to a {@link Book}
 * (by {@link #bookId}). The system enforces a "one copy per book" rule — a user
 * cannot add the same book to their cart twice.</p>
 *
 * <h3>Storage:</h3>
 * <p>Stored in-memory via {@link com.toptal.bookshopv2.repository.CartItemRepository}
 * using a {@link java.util.concurrent.ConcurrentHashMap}.</p>
 *
 * <h3>Expiry:</h3>
 * <p>Cart items have a time-to-live based on the {@link #addedAt} timestamp.
 * The {@link com.toptal.bookshopv2.service.CartExpiryScheduler} periodically removes
 * items older than {@code app.cart.expiry-minutes} (configured in {@code application.properties}).</p>
 *
 * <h3>Lifecycle:</h3>
 * <ol>
 *   <li>Added via {@code POST /api/cart/items/{bookId}}</li>
 *   <li>Removed manually via {@code DELETE /api/cart/items/{bookId}}</li>
 *   <li>Cleared automatically on checkout or expiry</li>
 * </ol>
 *
 * @author Nitish
 * @version 2.0
 * @see com.toptal.bookshopv2.repository.CartItemRepository
 * @see com.toptal.bookshopv2.service.CartService
 * @see com.toptal.bookshopv2.service.CartExpiryScheduler
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CartItem {

    /** Unique identifier, auto-generated by {@link com.toptal.bookshopv2.repository.CartItemRepository}. */
    private Long id;

    /** Foreign key reference to the {@link User} who owns this cart item. */
    private Long userId;

    /** Foreign key reference to the {@link Book} added to the cart. */
    private Long bookId;

    /**
     * Timestamp of when this item was added to the cart.
     * Used by {@link com.toptal.bookshopv2.service.CartExpiryScheduler} to determine
     * if the item has expired. Defaults to the current time.
     */
    @Builder.Default
    private LocalDateTime addedAt = LocalDateTime.now();
}
