package com.toptal.bookshopv2.model;

import lombok.*;

/**
 * Domain model representing a book category (genre) in the bookshop catalog.
 *
 * <p>Categories provide a way to organize books into logical groups (e.g., "Fiction",
 * "Science", "Technology"). Each {@link Book} references a category by its {@code id}.</p>
 *
 * <h3>Storage:</h3>
 * <p>Stored in-memory via {@link com.toptal.bookshopv2.repository.CategoryRepository}
 * using a {@link java.util.concurrent.ConcurrentHashMap}.</p>
 *
 * <h3>Constraints:</h3>
 * <ul>
 *   <li>Category names must be unique (case-insensitive)</li>
 *   <li>A category cannot be deleted if books reference it</li>
 * </ul>
 *
 * @author Nitish
 * @version 2.0
 * @see Book
 * @see com.toptal.bookshopv2.repository.CategoryRepository
 * @see com.toptal.bookshopv2.service.CategoryService
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Category {

    /** Unique identifier, auto-generated by {@link com.toptal.bookshopv2.repository.CategoryRepository}. */
    private Long id;

    /** Display name of the category. Must be unique (case-insensitive). */
    private String name;
}
