package com.toptal.bookshopv2.model;

import lombok.*;
import java.math.BigDecimal;

/**
 * Domain model representing a single line item within an {@link Order}.
 *
 * <p>Each order item records which {@link Book} was purchased and the price
 * at the time of purchase ({@link #priceAtPurchase}). This ensures that
 * historical order data remains accurate even if the book's price changes later.</p>
 *
 * <h3>Storage:</h3>
 * <p>Order items are stored as a nested list within their parent {@link Order} object
 * in the {@link com.toptal.bookshopv2.repository.OrderRepository}. Each item receives
 * a unique ID from a separate {@code AtomicLong} sequence.</p>
 *
 * <h3>Immutability:</h3>
 * <p>Once created during checkout, order items are never modified or deleted.
 * They serve as a permanent purchase receipt.</p>
 *
 * @author Nitish
 * @version 2.0
 * @see Order
 * @see com.toptal.bookshopv2.service.CartService#checkout
 * @see com.toptal.bookshopv2.dto.OrderResponse.OrderItemResponse
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderItem {

    /** Unique identifier, auto-generated by {@link com.toptal.bookshopv2.repository.OrderRepository}. */
    private Long id;

    /** Foreign key reference to the parent {@link Order}. Set automatically during order save. */
    private Long orderId;

    /** Foreign key reference to the {@link Book} that was purchased. */
    private Long bookId;

    /**
     * The price of the book at the time of purchase.
     * This value is captured from {@link Book#getPrice()} during checkout and never changes,
     * preserving an accurate record even if the book's current price is later modified.
     */
    private BigDecimal priceAtPurchase;
}
