package com.toptal.bookshopv2.model;

import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.*;

/**
 * Domain model representing a completed purchase order.
 *
 * <p>An order is created when a user checks out their shopping cart via
 * {@link com.toptal.bookshopv2.service.CartService#checkout}. It captures a snapshot
 * of the purchase: total price, timestamp, and individual {@link OrderItem}s with
 * prices locked at the time of purchase.</p>
 *
 * <h3>Storage:</h3>
 * <p>Stored in-memory via {@link com.toptal.bookshopv2.repository.OrderRepository}
 * using a {@link java.util.concurrent.ConcurrentHashMap}.</p>
 *
 * <h3>Lifecycle:</h3>
 * <ol>
 *   <li>User adds books to cart → {@link CartItem}s created</li>
 *   <li>User calls {@code POST /api/cart/checkout}</li>
 *   <li>Stock is decremented for each book, cart is cleared</li>
 *   <li>Order with {@link OrderItem}s is persisted — immutable after creation</li>
 * </ol>
 *
 * <h3>Concurrency:</h3>
 * <p>The checkout method is {@code synchronized} to prevent race conditions
 * when multiple users attempt to purchase the last copy of a book simultaneously.</p>
 *
 * @author Nitish
 * @version 2.0
 * @see OrderItem
 * @see com.toptal.bookshopv2.repository.OrderRepository
 * @see com.toptal.bookshopv2.service.CartService#checkout
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Order {

    /** Unique identifier, auto-generated by {@link com.toptal.bookshopv2.repository.OrderRepository}. */
    private Long id;

    /** Foreign key reference to the {@link User} who placed this order. */
    private Long userId;

    /** Sum of all {@link OrderItem#priceAtPurchase} values in this order. */
    private BigDecimal totalPrice;

    /** Timestamp of when the order was placed. Defaults to the current time. */
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    /**
     * Line items in this order. Each item records which book was purchased
     * and the price at the time of purchase. Defaults to an empty list.
     */
    @Builder.Default
    private List<OrderItem> items = new ArrayList<>();
}
