package com.toptal.bookshopv2.model;

import lombok.*;
import java.time.LocalDateTime;

/**
 * Domain model representing a registered user in the bookshop system.
 *
 * <p>Users are stored in-memory via {@link com.toptal.bookshopv2.repository.UserRepository}
 * using a {@link java.util.concurrent.ConcurrentHashMap}. Each user has a unique email
 * address that serves as their login credential and JWT subject claim.</p>
 *
 * <h3>Lifecycle:</h3>
 * <ol>
 *   <li>User registers via {@code POST /api/auth/register} → {@link com.toptal.bookshopv2.service.AuthService#register}</li>
 *   <li>Password is BCrypt-hashed before storage</li>
 *   <li>A default admin user ({@code admin@bookshop.com}) is created at startup by
 *       {@link com.toptal.bookshopv2.config.DataInitializer}</li>
 * </ol>
 *
 * <h3>Security integration:</h3>
 * <p>During JWT authentication, {@link com.toptal.bookshopv2.security.CustomUserDetailsService}
 * loads the user by email and converts the {@link #role} to a Spring Security
 * {@code ROLE_USER} or {@code ROLE_ADMIN} authority.</p>
 *
 * @author Nitish
 * @version 2.0
 * @see Role
 * @see com.toptal.bookshopv2.repository.UserRepository
 * @see com.toptal.bookshopv2.service.AuthService
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /** Unique identifier, auto-generated by {@link com.toptal.bookshopv2.repository.UserRepository}. */
    private Long id;

    /** User's email address. Used as the login username and JWT {@code sub} claim. Must be unique. */
    private String email;

    /** BCrypt-hashed password. Never stored or transmitted in plaintext. */
    private String password;

    /** Authorization role. Defaults to {@link Role#USER} for new registrations. */
    @Builder.Default
    private Role role = Role.USER;

    /** Timestamp of when the user account was created. Defaults to the current time. */
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();
}
